### ISSUE TITLE
Bug for activeHeight < 15 and length = 2

### ISSUE THREAD

**Issue by dchaebae** [tsepeti/react-native-dots-pagination#6]
Hi,

When length is set to 2 (width,height=15), then the right dot is clipped, as shown in the image.
<img width="50" alt="Screen Shot 2020-06-20 at 11 24 41 AM" src="https://user-images.githubusercontent.com/22950102/85205336-d2fa5780-b2e8-11ea-82dd-726c5d4ba80c.png">

Setting width, height to match the default for non-active (width,height=10), makes the dot offset in the Y.
<img width="67" alt="Screen Shot 2020-06-20 at 11 24 00 AM" src="https://user-images.githubusercontent.com/22950102/85205338-d5f54800-b2e8-11ea-82dc-fed9aa836bb9.png">

**Comment by yasaricli** [comment]
hello @dchaebae 

I plan to have a look at this issue in a couple days and it should be resolved with the next release.

thanks.

**Comment by dchaebae** [comment]
Sounds good, thanks!

**Comment by sentientmachin3** [comment]
I'm still facing this issue, using 4 dots and having the 3rd selected. Here's how I use it:
```
<View style={styles.dots}>
    <Dots length={4} active={3} activeColor={Colors.accent} passiveColor={Colors.disabledTextColor} />
</View>
```
which is fairly simple. I tried several configs, messing with `activeDotWidth/Height` but didn't find a solution.

**Comment by yasaricli** [comment]
@sentientmachin3 Can you share an image about it?

**Comment by ammarfaris** [comment]
by default, currently,  it already makes the dot offset in the Y-axis like the original poster stated and like the image shown for all platforms (ios, android, react-native-web) ... @yasaricli 

versions:
![Screenshot 2023-09-06 at 2 30 13 PM](https://github.com/yasaricli/react-native-dots-pagination/assets/1182205/bf5ca63e-57af-43b7-8f0f-938d49819a06)

 "expo": "~49.0.7",
 "react-native": "0.72.4",
